#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2023 Jani Nikula <jani@nikula.org>

set -eu

# We could clone the repo, but save some bandwidth by retrieving the latest tag
# via git ls-remote, and its date via git web interface.

GIT_URL="git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git"
WEB_URL="https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tag"

get_tag()
{
	git -c "versionsort.suffix=-" ls-remote --exit-code --refs --sort="version:refname" --tags "${GIT_URL}" "*.*" |\
		tail --lines=1 |\
		cut --delimiter="/" --fields=3
}

get_date()
{
	curl --silent "${WEB_URL}/?h=${1}" |\
		grep "tag date" |\
		sed "s|<tr><td>tag date</td><td>\(.*\)</td></tr>|\1|"
}

TAG=$(get_tag)
DATE=$(get_date "${TAG}")

echo $TAG
echo $DATE

./kernel-tea-leaves --tag="${TAG}" --date="${DATE}" > index.rst
rst2html.py --strict --no-raw index.rst > index.html
